{{- if .Values.secrets.webuiSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-webui.fullname" . }}-secrets
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
type: Opaque
data:
  webuiSecretKey: {{ .Values.secrets.webuiSecretKey | b64enc }}
{{- end }}